pr:
  autoCancel: true
  branches:
    include:
      - '*'
  paths:
    exclude:
      - .gitignore
      - ./*.md
      - ./*.yml
      - ./aws/*.ts

trigger: none

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

jobs:
  - job: ci
    continueOnError: false
    displayName: 'Continuous Integration'
    steps:
      - task: Cache@2
        inputs:
          key: 'yarn | "$(Agent.OS)" | yarn.lock'
          restoreKeys: |
            yarn | "$(Agent.OS)"
            yarn
          path: $(YARN_CACHE_FOLDER)
        displayName: Cache Yarn packages

      - script: |
          yarn build:ci
        displayName: 'Install Dependencies and Build'

      - script: |
          yarn test:ci
        displayName: 'Unit Test'

      - task: PublishTestResults@2
        condition: always()
        displayName: 'Publish Test Results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'junit.xml'

      - task: PublishCodeCoverageResults@1
        condition: always()
        displayName: 'Publish Code Coverage'
        inputs:
          codeCoverageTool: cobertura
          summaryFileLocation: 'coverage/cobertura-coverage.xml'
          reportDirectory: './coverage'

      - task: DockerCompose@0
        displayName: Docker Compose Up
        inputs:
          dockerComposeFile: docker-compose.yml
          dockerComposeCommand: up -d

      - script: |
          yarn --cwd ./integration/rabbitmq
          yarn test:integration --force-exit
        displayName: Integration Tests
