pr:
  autoCancel: true
  branches:
    include:
      - '*'
  paths:
    exclude:
      - .gitignore
      - ./*.md
      - ./*.yml
      - ./aws/*.ts

pool: node-docker

jobs:
  - job: ci
    continueOnError: false
    displayName: 'Continuous Integration'
    steps:
      - script: |
          yarn build:ci
        displayName: 'Install Dependencies and Build'

      - script: |
          yarn test:ci
        displayName: 'Unit Test'

      - task: PublishTestResults@2
        condition: always()
        displayName: 'Publish Test Results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'junit.xml'

      - task: PublishCodeCoverageResults@1
        condition: always()
        displayName: 'Publish Code Coverage'
        inputs: 
          codeCoverageTool: cobertura
          summaryFileLocation: 'coverage/cobertura-coverage.xml'
          reportDirectory: './coverage'

      - script: |
          docker-compose -f docker-compose.ci.yml up -d
          docker network connect golevelup-nestjs-network golevelup-nestjs-agent
          yarn --cwd ./integration/rabbitmq
          yarn test:ci:integration
        displayName: Integration Testing
        env:
          NODE_ENV: ci
        # failOnStderr: true

      - script: |
          docker network disconnect golevelup-nestjs-network golevelup-nestjs-agent
          docker-compose -f docker-compose.ci.yml down
        displayName: Cleanup
        failOnStderr: false
        condition: always()
        